apiVersion: v1
name: airflow
version: 1.11.0
appVersion: 2.7.0
description: The official Helm chart to deploy Apache Airflow, a platform to
  programmatically author, schedule, and monitor workflows
home: https://airflow.apache.org/
sources:
  - https://github.com/apache/airflow
icon: https://airflow.apache.org/images/airflow_dark_bg.png
keywords:
  - apache
  - airflow
  - workflow
  - scheduler
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
maintainers:
  - email: dev@airflow.apache.org
    name: Apache Airflow PMC
type: application
annotations:
  artifacthub.io/links: |
    - name: Documentation
      url: https://airflow.apache.org/docs/helm-chart/1.8.0/
  artifacthub.io/screenshots: |
    - title: DAGs View
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/dags.png
    - title: Datasets View
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/datasets.png
    - title: Grid View
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/grid.png
    - title: Graph View
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/graph.png
    - title: Calendar View
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/calendar.png
    - title: Variable View
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/variable_hidden.png
    - title: Gantt Chart
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/gantt.png
    - title: Task Duration
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/duration.png
    - title: Code View
      url: https://airflow.apache.org/docs/apache-airflow/2.7.0/_images/code.png
  artifacthub.io/changes: |
    - description: Add support for container security context
      kind: added
      links:
      - name: '#31043'
        url: https://github.com/apache/airflow/pull/31043
    - description: Validate ``executor`` and ``config.core.executor`` match
      kind: changed
      links:
      - name: '#30693'
        url: https://github.com/apache/airflow/pull/30693
    - description: Support ``minAvailable`` property for PodDisruptionBudget
      kind: changed
      links:
      - name: '#30603'
        url: https://github.com/apache/airflow/pull/30603
    - description: Add ``volumeMounts`` to dag processor ``waitForMigrations``
      kind: changed
      links:
      - name: '#30990'
        url: https://github.com/apache/airflow/pull/30990
    - description: Template extra volumes
      kind: changed
      links:
      - name: '#30773'
        url: https://github.com/apache/airflow/pull/30773
    - description: Fix webserver probes timeout and period
      kind: fixed
      links:
      - name: '#30609'
        url: https://github.com/apache/airflow/pull/30609
    - description: Add missing ``waitForMigrations`` for workers
      kind: fixed
      links:
      - name: '#31625'
        url: https://github.com/apache/airflow/pull/31625
    - description: Add missing ``priorityClassName`` to K8S worker pod template
      kind: fixed
      links:
      - name: '#31328'
        url: https://github.com/apache/airflow/pull/31328
    - description: Adding log groomer sidecar to dag processor
      kind: fixed
      links:
      - name: '#30726'
        url: https://github.com/apache/airflow/pull/30726
    - description: Do not propagate global security context to statsd and redis
      kind: fixed
      links:
      - name: '#31865'
        url: https://github.com/apache/airflow/pull/31865
    - description: 'Misc: Default Airflow version to 2.6.3'
      kind: changed
      links:
      - name: '#31979'
        url: https://github.com/apache/airflow/pull/31979
    - description: 'Misc: Use template comments for the chart license header'
      kind: changed
      links:
      - name: '#30569'
        url: https://github.com/apache/airflow/pull/30569
    - description: 'Misc: Align ``apiVersion`` and ``kind`` order in chart templates'
      kind: changed
      links:
      - name: '#31850'
        url: https://github.com/apache/airflow/pull/31850
    - description: 'Misc: Cleanup Kubernetes < 1.23 support'
      kind: changed
      links:
      - name: '#31847'
        url: https://github.com/apache/airflow/pull/31847
